<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">get_dir</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFIYXNoQ3Vyc29yIGlkYyA9IHBpcGVsaW5lLmdldEhhc2hDdXJzb3IoKTsKCgkvLyBHZXQg
aW5wdXQgdmFsdWVzCiAgIAlpZGMuZmlyc3QoKTsKCVN0cmluZyBrZXkgPSBpZGMuZ2V0S2V5KCk7
CgkKCVZhbHVlcyB2bCA9IFZhbHVlc0VtdWxhdG9yLmdldFZhbHVlcyhwaXBlbGluZSwga2V5KTsK
CVN0cmluZyBwa2cgPSBTZXJ2aWNlLmdldFBhY2thZ2VOYW1lKHZsKTsKCUZpbGUgZmwgPSBTZXJ2
ZXJBUEkuZ2V0UGFja2FnZUNvbmZpZ0Rpcihwa2cpOwoJU3RyaW5nIGNvbmZpZ19kaXIgPSBmbC5n
ZXRQYXRoKCk7CgoJdHJ5Cgl7CQoJCS8vIEdldCBsaXN0IG9mIGZpbGVzIGluIGEgZ2l2ZSBkaXJl
Y3RvcnkKICAgICAgICBGaWxlIGZuYW1lID0gbmV3IEZpbGUoY29uZmlnX2Rpcik7CiAgICAgICAg
U3RyaW5nW10gZmlsZV9saXN0ID0gZm5hbWUubGlzdCgpOwoJCWZuYW1lID0gbnVsbDsKCSAgIAlp
ZGMuZmlyc3QoKTsKCQlpZGMuaW5zZXJ0QWZ0ZXIoImNvbmZpZ19maWxlX2xpc3QiLCBmaWxlX2xp
c3QpOwoJfQoJY2F0Y2goRXhjZXB0aW9uIGUpCgl7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oZS5nZXRNZXNzYWdlKCkpOwoJfQoKCS8vIFNldHVwIG91dHB1dCBtZXNzYWdlCglpZGMuZmly
c3QoKTsKCWlkYy5pbnNlcnRBZnRlcigicGtnX2NvbmZpZyIsY29uZmlnX2RpciArIEZpbGUuc2Vw
YXJhdG9yKTsKCglpZGMuZGVzdHJveSgpOw==</value>
</Values>
